[delegation] add mobile view to banner
aptos-labs/explorer pull request #408
Opened 2023-03-17 21:08 UTC by jillxuu

https://user-images.githubusercontent.com/121921928/226049675-75cb709e-d25a-415a-ac3e-fea4aec39c6f.mov

2023-03-17 21:18 UTC, moonclavedev requested changes

2023-03-20 20:34 UTC, moonclavedev submitted a review, later dismissed
Almost there! 

Can we compare to what's in the Figma file for mobile design? Specifically:

- Margin to the left of the content
- Tertiary button visual alignment with the content (going to require negative translate-x or margin, I suggest something like `transform: translateX(-0.5rem);`
- Font weight appears to be bold, I believe it's normal weight in the Figma file

Thanks!

2023-03-28 20:53 UTC, jillxuu commented
> Almost there!
> 
> Can we compare to what's in the Figma file for mobile design? Specifically:
> 
> * Margin to the left of the content
> * Tertiary button visual alignment with the content (going to require negative translate-x or margin, I suggest something like `transform: translateX(-0.5rem);`
> * Font weight appears to be bold, I believe it's normal weight in the Figma file
> 
> Thanks!

thanks for the suggestion! super helpful! addressed first two feedbacks. for third one, i believe font weight is 400, which is normal

2023-04-05 21:03 UTC, 0xZihan approved these changes
Accept to unblock. LGTM

2023-04-05 21:24 UTC, merged