[explorer] /modules default to /modules/code
aptos-labs/explorer pull request #483
Opened 2023-04-24 15:43 UTC by 0xbe1

as we're about to add read and write, the current routes for /modules doesn't work.

current:
/account/:account/modules/:module

proposed:
/account/:account/modules/:action/:module (action is one of "code", "read" and "write")

see https://deploy-preview-483--aptos-explorer.netlify.app/account/0x1/modules/code/account?network=mainnet for an example

2023-04-24 21:46 UTC, jillxuu requested changes
could you check in the codebase and make sure you update the url for all `/modules` related url redirection? there are couple of them that need to get updated, otherwise, experience's broken.

i.e. go to the txn page, randomly click on a function name, right now its 404.

2023-04-24 21:46 UTC, jillxuu commented on src/ExplorerRoutes.tsx
> +            path=":address/modules/:modulesTab/:selectedModuleName"
makes sense to me, tho it could be a breaking change if other people used old urls to do something. but i think effect should be minimal.

2023-04-25 05:34 UTC, jillxuu reviewed
code lgtm, one thing i'd like to call out is that i was testing with view function interaction, but txn failed with 400.

2023-04-25 05:36 UTC, 0xbe1 commented
> code lgtm, one thing i'd like to call out is that i was testing with view function interaction, but txn failed with 400.

@jillxuu  can you show me how to reproduce the 400? also are you using devnet?

2023-04-25 06:17 UTC, jillxuu commented
Its on devnet and i was using the netlify built urls. Sent from my iPhoneOn Apr 24, 2023, at 10:36 PM, 0xbe1 ***@***.***> wrote:﻿

code lgtm, one thing i'd like to call out is that i was testing with view function interaction, but txn failed with 400.

@jillxuu  can you show me how to reproduce the 400? also are you using devnet?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-04-25 09:36 UTC, geekflyer requested changes
Let's' rename these module tab URLs to `code|run-entry|run-view` to align more with the terminology in CLI. Calling this `modules/read+write` is kinda confusing. See https://aptos-org.slack.com/archives/C040LV2NWQ4/p1680757174899329?thread_ts=1680740887.034249&cid=C040LV2NWQ4

Also can we add url navigation support? It's kinda annoying that currently if I'm let's say looking at the staking module I have to scroll all the way down whenever I switch between code|run-entry|run-view  to get to the staking module and I can't share a link to a specific function.

Lastly this just some thought - no action required - but from a general UX perspective I think separating run-entry and run-view into separate tabs adds clunkiness. They should be ideally in the same tab (maybe with some optional filtering if necessary).

2023-04-25 09:43 UTC, 0xbe1 commented
@geekflyer thx for the feedback.

> Let's' rename these module tab URLs to code|run-entry|run-view to align more with the terminology in CLI.

in cli we do `aptos move view` vs `aptos move run`. so if we want to align then we probably want to do code|run|view instead? btw not able to access the slack link since i am not in the slack group

> Also can we add url navigation support? It's kinda annoying that currently if I'm let's say looking at the staking module I have to scroll all the way down whenever I switch between code|run-entry|run-view to get to the staking module and I can't share a link to a specific function.

plan to support this in separate pr. step by step.

> separating run-entry and run-view into separate tabs is unnecessary

yep i think we can decide later. currently the code is in one place, so very easy to merge them into one

2023-04-25 10:11 UTC, geekflyer commented
> @geekflyer thx for the feedback.
> 
> > Let's' rename these module tab URLs to code|run-entry|run-view to align more with the terminology in CLI.
> 
> in cli we do `aptos move view` vs `aptos move run`. so if we want to align then we probably want to do code|run|view instead? btw not able to access the slack link since i am not in the slack group
> 
> > Also can we add url navigation support? It's kinda annoying that currently if I'm let's say looking at the staking module I have to scroll all the way down whenever I switch between code|run-entry|run-view to get to the staking module and I can't share a link to a specific function.
> 
> plan to support this in separate pr. step by step.
> 
> > separating run-entry and run-view into separate tabs is unnecessary
> 
> yep i think we can decide later. currently the code is in one place, so very easy to merge them into one

On 1.: Ok yeah code|run|view works. I would also suggest to rename the UI labels accordingly.

On 2.: Ok, but please make it a fast follow up. Sometimes it's hard to add these things after the fact then the code is structured in a certain way.

2023-04-25 12:23 UTC, 0xbe1 commented
@geekflyer fixed (1), ok to unblock?

2023-04-25 16:58 UTC, jillxuu approved these changes
comments in the scope of this PR are addressed. stamp to unblock.

Following AI is to add url navigation support so that move across tabs will persist the function/module

2023-04-25 17:32 UTC, geekflyer approved these changes

2023-04-25 23:39 UTC, merged