[txns] Fix navigation in transactions with back
aptos-labs/explorer pull request #965
Opened 2024-12-20 09:41 UTC by rs-8

Hello!

Fix back navigation in transactions page

For the first navigation to transactions, a replacement is used so that you can exit with one click

Navigations between user and all transactions work as usual

**Before:**

https://github.com/user-attachments/assets/249dcf58-1e16-4a82-840b-f9003621f296

**After**

https://github.com/user-attachments/assets/bd34345c-d35e-4aa4-81da-a34e0cba64b7

2025-01-06 23:57 UTC, kaw2k requested changes
Thank you for the before and after, and for contributing!

2025-01-06 23:57 UTC, kaw2k commented on src/pages/Transactions/Index.tsx
> +  }, [isGraphqlClientSupported, searchParams, setSearchParams, allTxnOnly]);
Just a touch of cleanup here:

* Looks like we no longer need `allTxnOnly` so we can omit it from the dependency array
* You should only return a [cleanup function](https://react.dev/reference/react/useEffect#parameters) from `useEffect`, otherwise, avoid returns. 

I suggest the following:

```tsx
useEffect(() => {
  if (!searchParams.get("type")) {
    searchParams.set("type", isGraphqlClientSupported ? "user" : "all");
    setSearchParams(searchParams, { replace: true });
  }
}, [isGraphqlClientSupported, searchParams, setSearchParams]);
```

2025-01-07 08:23 UTC, rs-8 commented on src/pages/Transactions/Index.tsx
> +  }, [isGraphqlClientSupported, searchParams, setSearchParams, allTxnOnly]);
Looks correct and simpler, added changes to pull request
Thank you for review

2025-01-07 17:28 UTC, kaw2k approved these changes
Excelent, thank you!

2025-01-07 17:28 UTC, merged